#pragma once
#include "../headers/uefi/uefi.h"

#define EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_REVISION    0x00010000
#define EFI_FILE_PROTOCOL_REVISION2                 0x00020000
#define EFI_FILE_PROTOCOL_LATEST_REVISION           EFI_FILE_PROTOCOL_REVISION2

typedef struct _EFI_SIMPLE_FILE_SYSTEM_PROTOCOL EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;