timeout: 1

/Ferrum Linux
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: console=ttyS0,115200n8 root=UUID=placeholder rw virtio_mmio.device=4K@0x20002000:5 virtio_mmio.device=4K@0x20003000:6
    module_path: boot():/initramfs-linux.img