#!/bin/sh

mkdir -p /newroot

mount -t proc proc /proc 2>/dev/null
mount -t sysfs sysfs /sys 2>/dev/null
mount -t devtmpfs devtmpfs /dev 2>/dev/null

mount /dev/vda2 /newroot
mount -t proc proc /newroot/proc
mount -t sysfs sysfs /newroot/sys
mount -t devtmpfs devtmpfs /newroot/dev

exec switch_root /newroot /bin/sh

exec /bin/sh
